spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    schema: classpath:/data.sql
    initialize: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
jdbc:
  url: jdbc:h2:mem:test
  name: sa
  password: ""